In [622]:
import pandas as pd
import numpy as np
import re

In [362]:
df = pd.read_csv('attacks.csv', encoding="latin-1")
df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [363]:
#shape
df.shape

(25723, 24)

In [364]:
#want to see all columns
pd.set_option('display.max_columns', 24)
df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [365]:
df.dtypes

Case Number                object
Date                       object
Year                      float64
Type                       object
Country                    object
Area                       object
Location                   object
Activity                   object
Name                       object
Sex                        object
Age                        object
Injury                     object
Fatal (Y/N)                object
Time                       object
Species                    object
Investigator or Source     object
pdf                        object
href formula               object
href                       object
Case Number.1              object
Case Number.2              object
original order            float64
Unnamed: 22                object
Unnamed: 23                object
dtype: object

In [366]:
#HUGE PERCENTAGES OF EMPTY FIELDS
df.isnull().sum()/len(df)

Case Number               0.661704
Date                      0.755005
Year                      0.755083
Type                      0.755161
Country                   0.756949
Area                      0.772694
Location                  0.775998
Activity                  0.776154
Name                      0.763169
Sex                       0.776970
Age                       0.865062
Injury                    0.756094
Fatal (Y/N)               0.775959
Time                      0.885394
Species                   0.865335
Investigator or Source    0.755666
pdf                       0.755005
href formula              0.755044
href                      0.755005
Case Number.1             0.755005
Case Number.2             0.755005
original order            0.754733
Unnamed: 22               0.999961
Unnamed: 23               0.999922
dtype: float64

In [367]:
#WHICH ROWS ARE COMPLETLY EMPTY
df[df.isnull().sum(axis=1)>len(df.columns)]

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23]
Index: []

In [368]:
#GETTING RID OF ALL ROWS THAT HAVE ONLY NaN values
df_1=df[df.isnull().sum(axis=1)<len(df.columns)]
df_1

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8698,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8699,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8700,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8701,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [369]:
#PERCENTAGES OF EMPTY FIELDS PER COLUMN IMPROVED

df_1.isnull().sum()/len(df)

Case Number               0.000039
Date                      0.093341
Year                      0.093418
Type                      0.093496
Country                   0.095284
Area                      0.111029
Location                  0.114333
Activity                  0.114489
Name                      0.101504
Sex                       0.115305
Age                       0.203398
Injury                    0.094429
Fatal (Y/N)               0.114295
Time                      0.223730
Species                   0.203670
Investigator or Source    0.094001
pdf                       0.093341
href formula              0.093379
href                      0.093341
Case Number.1             0.093341
Case Number.2             0.093341
original order            0.093068
Unnamed: 22               0.338296
Unnamed: 23               0.338258
dtype: float64

In [370]:
#checking 'Unnamed: 22', 'Unnamed: 23'

In [371]:
df_1[df_1['Unnamed: 22'].notnull()]
df_1[df_1['Unnamed: 23'].notnull()]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
4415,1952.03.30,30-Mar-1952,1952.0,Unprovoked,NETHERLANDS ANTILLES,Curacao,NaN,Went to aid of child being menaced by the shark,A.J. Eggink,M,NaN,"Buttock bitten, tissue removed",N,NaN,"Bull shark, 2.7 m [9'] was captured & dragged ...","J. Randall, p.352 in Sharks & Survival; H.D. B...",1952.03.30-Eggink.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1952.03.30,1952.03.30,1888.0,NaN,Teramo
5840,1878.09.14.R,Reported 14-Sep-1878,1878.0,Provoked,USA,Connecticut,"Branford, New Haven County",Fishing,Captain Pattison,M,NaN,Leg bitten by netted shark PROVOKED INCIDENT,N,NaN,NaN,"St. Joseph Herald, 9/14/1878",1878.09.14.R-Pattison.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1878.09.14.R,1878.09.14.R,463.0,NaN,change filename

In [372]:
#Dropping 'Unnamed: 22', 'Unnamed: 23'
df_1=df_1.drop(['Unnamed: 22', 'Unnamed: 23'], axis=1)

In [373]:
df_1

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8698,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8699,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8700,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8701,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [374]:
#original order column: What is in there? Cant make sense of it. Lets drop
df_1['original order'][df_1['original order'].notnull()]

0       6303.0
1       6302.0
2       6301.0
3       6300.0
4       6299.0
         ...
6304    6306.0
6305    6307.0
6306    6308.0
6307    6309.0
6308    6310.0
Name: original order, Length: 6309, dtype: float64

In [375]:
#DROP COLUMN ORIGINAL ORDER
df_1=df_1.drop(['original order'], axis=1)

In [376]:
df_1.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04

In [377]:
#2400 'Case Number' have value '0'. are they strongly associated with empty records?
df_1['Case Number'].value_counts()

0               2400
2013.10.05         2
1962.06.11.b       2
1907.10.16.R       2
1923.00.00.a       2
                ...
1909.01.00         1
1997.12.28.a       1
1912.08.30         1
2013.02.27         1
1987.04.01         1
Name: Case Number, Length: 6287, dtype: int64

In [378]:
df_1[(df_1.isnull().sum(axis=1)>len(df_1.columns)-2)]
#2401 records have only a single value other than NaN

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2
6302,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6303,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6304,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6305,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6306,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8698,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8699,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8700,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8701,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [379]:
df_1['Case Number'][(df_1.isnull().sum(axis=1)>len(df_1.columns)-2)]
#for 2400 rows with just a single valid value this value is a '0' in the Case Number column, 
# for 1 row ith just a single valid value this value is 'xx' in the Case Number column

6302      0
6303      0
6304      0
6305      0
6306      0
         ..
8698      0
8699      0
8700      0
8701      0
25722    xx
Name: Case Number, Length: 2401, dtype: object

In [380]:
#LETS DELETE 'EM COLUMNS WITH '0' and 'xx' in the Case Number column
df_2=df_1[df_1['Case Number']!='0']
df_2['Case Number'].value_counts()

2013.10.05      2
2006.09.02      2
1913.08.27.R    2
2014.08.02      2
1983.06.15      2
               ..
1909.01.00      1
1997.12.28.a    1
1912.08.30      1
2013.02.27      1
1987.04.01      1
Name: Case Number, Length: 6286, dtype: int64

In [381]:
df_3=df_2[df_2['Case Number']!='xx']
df_3['Case Number'].value_counts()

2013.10.05      2
1962.06.11.b    2
1913.08.27.R    2
2014.08.02      2
1983.06.15      2
               ..
1997.12.28.a    1
1912.08.30      1
2013.02.27      1
2015.06.14.b    1
1987.04.01      1
Name: Case Number, Length: 6285, dtype: int64

In [382]:
df_3.shape

(6302, 21)

In [383]:
#CHECKIN 'Case Number.1' 'Case Number.2' ARE THEY IDENTICAL

In [384]:
#In 6282 cases 'Case Number.1' 'Case Number.2' are identical, In 20 cases different
df_3[df_3['Case Number.1']==df_3['Case Number.2']]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001

In [393]:
#Lets look at the records where they are different
df_3[df_3['Case Number.1']==df_3['Case Number.2']].shape
#seems they are considered different  when they both are NaN

(6282, 21)

In [394]:
df_3[df_3['Case Number.1']!=df_3['Case Number.2']].shape

(20, 21)

In [404]:
df_3[df_3['Case Number.1']!=df_3['Case Number.2']]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2
34,2018.04.03,03-Apr-2018,2018.0,Unprovoked,SOUTH AFRICA,Eastern Cape Province,St. Francis Bay,Surfing,Ross Spowart,M,19,Lacerations to left knee & lower leg,N,15h00,White shark,"K. McMurray, TrackingSharks.com",2018.04.03-StFrancisBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.02,2018.04.03
35,2018.03.31,31-Mar-2018,2018.0,Unprovoked,USA,Hawaii,Kukio Beach,Stand-Up Paddleboarding,male,M,25,Injuries to right leg & hand,N,09h30,"Tiger shark, 12'","Khon2, 3/31/2018",2018.03.31-Hawaii.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.03,2018.03.31
117,2017.07.20.a,20-Jul-2017,2017.0,Unprovoked,USA,California,"Seal Rock, Goleta Beach, Santa Barbara",SUP,Rolf Geyling,M,50,"No injury, shark bit paddleboard",N,07h45,"White shark, 8' to 10'","R. Collier, GSAF",2017.07.20.a-Geyling.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017/07.20.a,2017.07.20.a
144,2017.05.06,05-May-2017,2017.0,Unprovoked,MEXICO,Baja California Sur,"Los Arbolitos, Cabo Pulmo",Snorkeling,Andres Rozada,M,33,FATAL,Y,17h00,NaN,J. Rozada,2017.05.06-Rozada.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.06,2017.05.06
217,2016.09.15,16-Sep-2016,2016.0,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15
314,2016.01.24.b,24-Jan-2016,2016.0,Unprovoked,USA,Texas,Off Surfside,Spearfishing,Keith Love,M,NaN,"Bruised ribs & tail bone, speargun broken and ...",N,09h30 / 10h00,Bull sharks x 2,K. Love,2016.01.24.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.01.24.b,2016.01.24.b
334,2015.12.23,07-Nov-2015,2015.0,Invalid,USA,Florida,"Paradise Beach, Melbourne, Brevard County",Surfing,Ryla Underwood,F,9,Lower left leg injured,NaN,11h00,Shark involvement not confirmed,"Fox25Orlando, 11/7/2015",2015.11.07-Underwood.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.11.07,2015.12.23
339,2015.10.28.a,28-Oct-2015,2015.0,Unprovoked,USA,Hawaii,"Malaka, Oahu",Body boarding,Raymond Senensi,M,10,"Lacerations & puncture wounds to right thigh, ...",N,14h50,NaN,"Star Advertiser, 10/28/2015",2015.10.28-Senensi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.10.28,2015.10.28.a
560,2014.05.04,04-May-2014,2014.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Simonstown,Diving,NaN,NaN,NaN,4-inch laceration to arm,N,NaN,Cow shark,"Sunday Times, 5/5/2014",2015.05.04-CowShark.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2013.05.04,2014.05.04
3522,1967.07.05,05-Jul-1967,1967.0,Unprovoked,TURKEY,Mugla Province,Kucukada Island,Spearfishing,Gungor Guven,M,36,FATAL,Y,13h40,NaN,"C. Moore, GSAF",1967.07.05-Guven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1967/07.05,1967.07.05
3795,"1962,08.30.b",30-Aug-1962,1962.0,Boat,TURKEY,Antalya Province,Ucagiz,NaN,Occupant: Hasan Olta,M,NaN,No injury,N,NaN,NaN,"C.Moore, GSAF",1962.08.30.b-pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1962.08.30.b,"1962,08.30.b"
3880,1961.09.02.R,Reported 06-Sep-1961,1961.0,Provoked,ITALY,Venice Province,Chioggia,Fishing,Pollione Perrini & Fioravante Perini,M,33 & 37,Left foot & right hand bitten by netted shark ...,N,NaN,1 m shark,"C. Moore, GSAF",1961.09.06.R-Chioggia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,"1961.09,06.R",1961.09.02.R
4403,1952.08.05,05-Aug-1952,1952.0,Provoked,ITALY,Teramo,Giulianova,Fishing,Vittorio Speca,NaN,19,Multiple injuries PROVOKED INCIDENT,Y,02h00,2m shark,"C. Moore, GSAF",1952.08.05-Speca.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1952.08.04,1952.08.05
4425,1851.12.15.R,\n1951.12.15.R,1951.0,Invalid,MOZAMBIQUE,Sofala Province,Beira,Swimming,Antonio De Almeida Pinto,M,NaN,No injury,NaN,NaN,Invalid,GSAF,1951.12.15.R-Pinto.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1951.12.15.R,1851.12.15.R
5275,1900.00.00.R,Reported to have taken place in 1919,1919.0,Boating,ITALY,NaN,Savona,Fishing,NaN,M,NaN,No injury,N,NaN,13' shark,"C. Moore, GSAF",1919.00.00.R-Savona.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1919.00.00.R,1900.00.00.R
5358,1913.07.10.R,Reported 10-Jul-1913,1913.0,Unprovoked,COSTA RICA,NaN,Port Limon,Swimming,August Schulke & Karl Schafer,M,NaN,FATAL,Y,NaN,NaN,"The Potter Enterprise, 7/10/1913",1913.07.10.R-PortLimon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1913.17.10.R,1913.07.10.R
5386,1911.07.31.R,Reported 31-Jul-1911,1911.0,Unprovoked,SPAIN,Málaga,Ceuta,Bathing,a soldier,M,NaN,FATAL,Y,NaN,NaN,C. Moore. GSAF,1911.07.31.R-Ceuta.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1911.07.31.T,1911.07.31.R
5777,1884.04.38.R,Reported 28-Apr-1884,1884.0,Unprovoked,BRAZIL,NaN,Bahia,Fell overboard from the steamship Chala,male,M,NaN,FATAL,Y,NaN,NaN,"Pittsburgh Post Gazette, 4/28/1884",1884.04.28.R-ChalaCook.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1884.04.28.R,1884.04.38.R
5883,1876.06.18.R,Reported 18-Jun- 1874,1874.0,Unprovoked,MEXICO,Veracruz,"Tlacotalpan, Vera Cruz",Bathing,a servant of General Diaz,M,NaN,FATAL,Y,NaN,NaN,"The Times-Picayune, 6/18/1874",1874.06.18.R-DiazServant.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1874.06.18.R,1876.06.18.R
6009,"1853,94.29",29-Apr-1853,1853.0,Unprovoked,GREECE,Corfu,NaN,Swimming,Hanson,M,NaN,Leg severed at knee,N,NaN,234-lb shark,"South Australian Register, 5/8/1854",1853.04.29-Hanson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1853.04.29,"1853,94.29"
6122,1808.06.01.R,Reported 01-May-1808,1808.0,Sea Disaster,ANTIGUA,NaN,Falmouth Harbour,NaN,NaN,NaN,NaN,Probable drowning & scavenging,NaN,NaN,NaN,"London Observer, 5/1/1808",1808.05.01.R-Antigua.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1808.05.01.R,1808.06.01.R

In [ ]:
#HARMONIZING 'Case Number.1','Case Number.2','Case Number'

df_3.loc[3522,['Case Number.1','Case Number.2','Case Number']]='1967.07.05'
df_3[['Case Number.2','Case Number']][3795]='1962.08.30.b'
df_3[['Case Number.1']][3880]='1961.09.02.R'
df_3[['Case Number.1']][4403]='1952.08.05'
df_3.loc[4425,['Case Number.2','Case Number']]='1951.12.15.R'
#df_3[['Case Number.1']][5275]='1918.03.22'
df_3.loc[5275,['Case Number.1','Case Number.2','Case Number']]='1918.03.22'
df_3.loc[3795,['Case Number.1','Case Number.2','Case Number']]='1962.08.30.b'
df_3.loc[3880,['Case Number.1','Case Number.2','Case Number']]='1961.09.02.R'
df_3.loc[4403,['Case Number.1','Case Number.2','Case Number']]='1952.08.05'
df_3.loc[5358,['Case Number.1','Case Number.2','Case Number']]='1913.07.10.R'
df_3.loc[5386,['Case Number.1','Case Number.2','Case Number']]='1911.07.31.R'
df_3.loc[5777,['Case Number.1','Case Number.2','Case Number']]='1884.04.28.R'
df_3.loc[5883,['Case Number.1','Case Number.2','Case Number']]='1874.06.18.R'
df_3.loc[6009,['Case Number.1','Case Number.2','Case Number']]='1853.04.29'
df_3.loc[6122,['Case Number.1','Case Number.2','Case Number']]='1808.05.01.R'
df_3.loc[217,['Case Number.1','Case Number.2','Case Number']]='2016.09.15'
df_3.loc[334,['Case Number.1','Case Number.2','Case Number']]='2015.11.07'
df_3.loc[390,['Case Number.1','Case Number.2','Case Number']]='2015.07.10'
df_3.loc[4949,['Case Number.1','Case Number.2','Case Number']]='1924.02.08.R'
df_3.loc[5488,['Case Number.1','Case Number.2','Case Number']]='1905.09.06.R'
df_3.loc[5944,['Case Number.1','Case Number.2','Case Number']]='1864.05.00.R'

In [ ]:
df_3[['Case Number.1','Case Number.2','Case Number','Date','Year','Location','href']][df_3['Case Number.2']!=df_3['Case Number']]

In [478]:
#CHECKING COLUMNS Fatal (Y/N)
#11 odd values '2017' 'y' 'N ' ' N' 'M'
df_3['Fatal (Y/N)'].value_counts()

N          4293
Y          1388
UNKNOWN      71
 N            7
y             1
N             1
2017          1
M             1
Name: Fatal (Y/N), dtype: int64

In [496]:
#LOOKING AT ALL ROWS WITH FATAL VALUES OTHER THAN Y N UNKNOWN
df_3[(df_3['Fatal (Y/N)'] =='2017') | (df_3['Fatal (Y/N)'] =='y') | (df_3['Fatal (Y/N)'] =='M') | (df_3['Fatal (Y/N)'] ==' N')]

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2]
Index: []

In [499]:
list(df_3[(df_3['Fatal (Y/N)'] ==' N')] .index)
df_3.loc[list(df_3[(df_3['Fatal (Y/N)'] ==' N')] .index),'Fatal (Y/N)']='N'
df_3.loc[list(df_3[(df_3['Fatal (Y/N)'] =='N ')] .index),'Fatal (Y/N)']='N'
df_3.loc[list(df_3[(df_3['Fatal (Y/N)'] =='M')] .index),'Fatal (Y/N)']='N'
df_3.loc[list(df_3[(df_3['Fatal (Y/N)'] =='y')] .index),'Fatal (Y/N)']='Y'
df_3.loc[list(df_3[(df_3['Fatal (Y/N)'] =='2017')] .index),'Fatal (Y/N)']='N'

/Users/spitzer/opt/anaconda3/envs/kittycat/lib/python3.8/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [500]:
df_3['Fatal (Y/N)'].value_counts()

N          4303
Y          1389
UNKNOWN      71
Name: Fatal (Y/N), dtype: int64

In [502]:
#539 NaN VALUES IN COLUMN 'Fatal (Y/N)' nicht bedacht dass die beim Value count nicht berücksichtigt werden
df_3[df_3['Fatal (Y/N)'].isnull()]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c
76,2017.10.01,01-Oct-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Dyer Island,Scuba Diving,Bradley Fick,M,31,FATAL,NaN,NaN,Death may have been due to drowning,"All Africa, 10/11/2017",2017.10.01-Fick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.01,2017.10.01
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,USA,New York,Rockaway,Surfing,Michah Behrend,M,33,"Lacerations to right ankle, foot & toe",NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b
84,2017.09.15.b,15-Sep-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Hawston,Scuba Diving,Wayon Love,M,25,"FATAL, but death was probably due to drowning",NaN,Afternoon,NaN,"Ground Up, 9/20/2017",2017.09.15.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.b,2017.09.15.b
98,2017.08.26.b,26-Aug-2017,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Lacerations to left foot,NaN,Midday,Shark involvement questionable,"El Periodico Mediterraneo, 8/27/2017",2017.08.26.b-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b,2017.08.26.b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6147,1767.00.00,1767,1767.0,Invalid,FRANCE,Côte d'Azur,St. Tropez,Bathing,Samuel Matthews,M,NaN,Lacerations to arm & leg,NaN,NaN,Description of shark does not ring true,NaN,1767.00.00-Matthews.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1767.00.00,1767.00.00
6157,1733.00.00,1733,1733.0,Invalid,ICELAND,Bardestrand,Talkknefiord,NaN,NaN,NaN,NaN,"Partial hominid remains recovered from shark, ...",NaN,NaN,Shark involvement prior to death unconfirmed,E. Olafsen,1733.00.00-Iceland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1733.00.00,1733.00.00
6158,1723.00.00,1723,1723.0,Unprovoked,ROATAN,NaN,NaN,NaN,Philip Ashton,M,NaN,Struck on thigh,NaN,NaN,NaN,"C.Moore, GSAF",1730.00.00-Ashton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1723.00.00,1723.00.00
6164,1642.00.00.b,Late 1600s Reported 1728,1642.0,Invalid,GUINEA,NaN,NaN,Went overboard,crew member of the Nieuwstadt,M,NaN,FATAL,NaN,NaN,Questionable,"History of the Pyrates, by D. Defoe, Vol. 2, p.28",1642.00.00.b-Nieuwstadt.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1642.00.00.b,1642.00.00.b
6232,ND.0081,"No date, Before 1963",0.0,Invalid,USA,Hawaii,"Portlock, Oahu",Diving,Val Valentine,M,NaN,A 4.3 m [14'] shark made threat display. No in...,NaN,NaN,Invalid,B. Sojka & D. Lloyd,ND-0081-Valentine.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0081,ND.0081

In [573]:
# TO FILL SOME OF THE EMPTY 'Fatal (Y/N)' feilds we could get 'help from the injury column
#as injury column provides additionl info
# lets find the word fatal in the relevant injury cells

df_3[df_3.Injury.str.lower().str.contains('fatal')]
#Suche nach fatal String doesnt work as long as there are NaN values is 'Injury'
#SUBSTITUTED ALL NAN Values is Injurys with '0' so i could search for fatal
# 1362 records with the word 'fatal' in injurys column

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a
58,2017.11.30.a,30-Nov-2017,2017.0,Unprovoked,COSTA RICA,Cocos Island,Manuelita,Scuba diving,Rohina Bhandari,F,49,FATAL,Y,NaN,"Tiger shark, female",R. Arauz,2017.11.30.a-Bhandari.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.11.30.a,2017.11.30.a
59,2017.11.25.R,Reported 25-Nov-2017,2017.0,Sea Disaster,LIBYA,NaN,Gars Garabulli,2 boats capsized,31 migrants,NaN,NaN,FATAL,Y,NaN,Some drowned but other may have been killed by...,"TG Com 24, 11/25/2017",2017.11.25.R-Libya.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.11.25.R,2017.11.25.R
64,2017.11.04,04-Nov-2017,2017.0,Unprovoked,CUBA,Holquin Province,Guardalavaca Beach,Night bathing,Jesús Cabrera González,M,22,FATAL,Y,23h30,Tiger shark,TrackingSharks.com,2017.11.04-Cuba.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.11.04,2017.11.04
76,2017.10.01,01-Oct-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Dyer Island,Scuba Diving,Bradley Fick,M,31,FATAL,NaN,NaN,Death may have been due to drowning,"All Africa, 10/11/2017",2017.10.01-Fick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.01,2017.10.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001

In [572]:
df_3.Injury.isnull().value_counts()

False    6302
Name: Injury, dtype: int64

In [ ]:
#EFFORT: Set all NaN to '0' hoping I can search for 'fatal' then >> WORKED!
df_3['Injury'][df_3.Injury.isnull()]='0'

In [539]:
#LINE TO READ Injury Note in full length
df_3.loc[159,'Injury']

'Fatal, coroner unable to determine if the diver was alive or had drowned when incident took place.'

In [ ]:
df_3.loc[5944,['Case Number.1','Case Number.2','Case Number']]='1864.05.00.R'

In [564]:
#ARE THERE ROWS CONTAINING THE WORD FATAL IN 'INJURY' WHERE 'Fatal (Y/N)' has no information???
df_3[['Injury','Fatal (Y/N)']][(df_3.Injury.str.lower().str.contains('fatal')) & (df_3['Fatal (Y/N)'].isnull())]
#YES!!! 52 Records have empty 'Fatal (Y/N)' but strongly indicate fatality in Injury field

                                                 Injury Fatal (Y/N)
76                                                FATAL         NaN
84        FATAL, but death was probably due to drowning         NaN
159   Fatal, coroner unable to determine if the dive...         NaN
437   FATAL, but shark involvement prior to death un...         NaN
874                                               FATAL         NaN
1495  FATAL, but shark involvement prior to death un...         NaN
1563  FATAL, shark involvement prior to death is unc...         NaN
1879                 PRESUMED FATAL, body not recovered         NaN
1947      Fatal or drowned & remains scavenged by shark         NaN
2025                                          Non-fatal         NaN
2230                                              FATAL         NaN
2660                                              FATAL         NaN
2674                                              FATAL         NaN
2791                                              FATAL         NaN
2890  FATAL, but shark involvement prior to death co...         NaN
2897   Forced at gunpoint to jump overboard. Presume...         NaN
2953                                              FATAL         NaN
3095  FATAL, but shark involvement prior to death wa...         NaN
3112  FATAL or scavenging by 3 m tiger shark (may ha...         NaN
3532          Fatal or scavenging by "a pack of sharks"         NaN
3811                                              FATAL         NaN
3947  FATAL, probable drowning & post mortem scavenging         NaN
4211         FATAL, but shark involvement not confirmed         NaN
4213      FATAL, but was it an accident or infanticide?         NaN
4501                    Fatal or drowning or scavenging         NaN
4780                                              FATAL         NaN
4900  Although listed as an uprovoked fatal attack b...         NaN
4901  Although listed as  an uprovoked fatal attack ...         NaN
4934  Reported  to be FATAL and involve a 6m white s...         NaN
5116                   FATAL, presumed taken by shark/s         NaN
5196                                              FATAL         NaN
5218  FATAL, but shark involvement prior to death un...         NaN
5329                      Fatal, drowning or scavenging         NaN
5396                                             FATAL?         NaN
5425                                              FATAL         NaN
5439  FATAL, but shark involvement prior to death wa...         NaN
5499                                              FATAL         NaN
5577                                              FATAL         NaN
5578                                              FATAL         NaN
5590  Reported fatal, but this is a questionable inc...         NaN
5671                           Fatal, probable drowning         NaN
5692     Fatal, but death may have been due to drowning         NaN
5695     Fatal, but death may have been due to drowning         NaN
5806                                              FATAL         NaN
5825                                             FATAL          NaN
5891                                              FATAL         NaN
5906                                              FATAL         NaN
5918  Shark bit canoe in half & bit man. Note: There...         NaN
5920                                              FATAL         NaN
5951                                     Presumed FATAL         NaN
6104                                              FATAL         NaN
6164                                              FATAL         NaN

In [598]:
#'INJURY' COMMENT CONTAINS DETAILED INFORMATION
# that deliver context and questions if fatality really occured due to shark attack
# 1st step: if 'Injury' just says 'FATAL' set  'Fatal (Y/N)' to 'Y'
#df_3[(df_3['Injury']=='FATAL') & (df_3['Fatal (Y/N)'].isnull())]#Datafram where Injury value FATAL and Fatal (Y/N) NaN
list(df_3[(df_3['Injury']=='FATAL') & (df_3['Fatal (Y/N)'].isnull())].index)#List of indexes where Injury value FATAL and Fatal (Y/N) NaN

[76,
 874,
 2230,
 2660,
 2674,
 2791,
 2953,
 3811,
 4780,
 5196,
 5425,
 5499,
 5577,
 5578,
 5806,
 5891,
 5906,
 5920,
 6104,
 6164]

In [ ]:
#USE LIST OF INDEXES to assign value 'Y' to 'Fatal (Y/N)' where Fatal (Y/N)' is NaN but 'Injury'== 'FATAL'
df_3.loc[list(df_3[(df_3['Injury']=='FATAL') & (df_3['Fatal (Y/N)'].isnull())].index),['Fatal (Y/N)']]='Y'
#ALSO ASSIGNING N to 'Fatal (Y/N)'  where Injury says 'Non-Fatal'
df_3.loc[2025,['Fatal (Y/N)']]='N'

In [623]:
#NOW LETS COMPARE Injury and Fatal (Y/N) columns again
df_3[['Injury','Fatal (Y/N)']][(df_3.Injury.str.lower().str.contains('fatal')) & (df_3['Fatal (Y/N)'].isnull())]
#THOSE NEED FURTHER CONSIDERATION ON HOW TO CATAGORIZE COMMENTS OF UNCERTEINTIY

                                                 Injury Fatal (Y/N)
84        FATAL, but death was probably due to drowning         NaN
159   Fatal, coroner unable to determine if the dive...         NaN
437   FATAL, but shark involvement prior to death un...         NaN
1495  FATAL, but shark involvement prior to death un...         NaN
1563  FATAL, shark involvement prior to death is unc...         NaN
1879                 PRESUMED FATAL, body not recovered         NaN
1947      Fatal or drowned & remains scavenged by shark         NaN
2890  FATAL, but shark involvement prior to death co...         NaN
2897   Forced at gunpoint to jump overboard. Presume...         NaN
3095  FATAL, but shark involvement prior to death wa...         NaN
3112  FATAL or scavenging by 3 m tiger shark (may ha...         NaN
3532          Fatal or scavenging by "a pack of sharks"         NaN
3947  FATAL, probable drowning & post mortem scavenging         NaN
4211         FATAL, but shark involvement not confirmed         NaN
4213      FATAL, but was it an accident or infanticide?         NaN
4501                    Fatal or drowning or scavenging         NaN
4900  Although listed as an uprovoked fatal attack b...         NaN
4901  Although listed as  an uprovoked fatal attack ...         NaN
4934  Reported  to be FATAL and involve a 6m white s...         NaN
5116                   FATAL, presumed taken by shark/s         NaN
5218  FATAL, but shark involvement prior to death un...         NaN
5329                      Fatal, drowning or scavenging         NaN
5396                                             FATAL?         NaN
5439  FATAL, but shark involvement prior to death wa...         NaN
5590  Reported fatal, but this is a questionable inc...         NaN
5671                           Fatal, probable drowning         NaN
5692     Fatal, but death may have been due to drowning         NaN
5695     Fatal, but death may have been due to drowning         NaN
5918  Shark bit canoe in half & bit man. Note: There...         NaN
5951                                     Presumed FATAL         NaN

In [ ]:
#I decided to introduce a 3rd catagory 'uncertain' in Fatal (Y/N)
#list of index with Injury notes hinting at uncertainty if fatality was caused by shark
list(df_3[['Injury','Fatal (Y/N)']][(df_3.Injury.str.lower().str.contains('fatal')) & (df_3['Fatal (Y/N)'].isnull())].index)
#ASSIGNING 'uncertain'
df_3.loc[list(df_3[['Injury','Fatal (Y/N)']][(df_3.Injury.str.lower().str.contains('fatal')) & (df_3['Fatal (Y/N)'].isnull())].index),['Fatal (Y/N)']]='uncertain'

In [647]:
#still 487 records with 'Fatal (Y/N)' NaN. I think this field is importan for analysis.
# Injury is providing further hints  but harder to systematically apply than the string 'fatal'
#found the string 'no injury' to be helpfull. It definately indicates non fatal attacks
#'no injury' string found in 88 records. Some descriptions questioning if it was an attack at all
df_3[['Injury','Fatal (Y/N)']][(df_3.Injury.str.lower().str.contains('no injury')) & (df_3['Fatal (Y/N)'].isnull())]

                                                 Injury Fatal (Y/N)
206             Shark breached cage, no injury to diver         NaN
226      No injury to divers, white shark breached cage         NaN
265                            No injury, board damaged         NaN
269   No injury, but sharks repeatedly hit their fin...         NaN
291   Fell off board when spinner shark leapt from t...         NaN
...                                                 ...         ...
5897                                          No injury         NaN
5945                                          No injury         NaN
6005  No injury & although reported as an attack, it...         NaN
6110                              No injury / No attack         NaN
6232  A 4.3 m [14'] shark made threat display. No in...         NaN

[88 rows x 2 columns]

In [ ]:
#list of indexes that contain string no injury with Fatal (Y/N) being NaN
list(df_3[['Injury','Fatal (Y/N)']][(df_3.Injury.str.lower().str.contains('no injury')) & (df_3['Fatal (Y/N)'].isnull())].index)

In [ ]:
# been brwosing those injury comments bei index
# decide to assign 'N' to 'Fatal (Y/N)' where 'Injury' contains string 'n'

df_3.loc[list(df_3[['Injury','Fatal (Y/N)']][(df_3.Injury.str.lower().str.contains('no injury')) & (df_3['Fatal (Y/N)'].isnull())].index), 'Fatal (Y/N)'] = 'N'

In [693]:
#still 399 records with ['Fatal (Y/N)'] NaN
df_3[df_3['Fatal (Y/N)'].isnull()]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,USA,New York,Rockaway,Surfing,Michah Behrend,M,33,"Lacerations to right ankle, foot & toe",NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b
98,2017.08.26.b,26-Aug-2017,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Lacerations to left foot,NaN,Midday,Shark involvement questionable,"El Periodico Mediterraneo, 8/27/2017",2017.08.26.b-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b,2017.08.26.b
107,2017.07.29.c,29-Jul-2017,2017.0,Invalid,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Johnny Simatacolos,M,10,Abrasions and cuts to sole of foot,NaN,15h00,A small shark,"C. Creswell, GSAF",2017.07.29.c-Simatacolos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.29.c,2017.07.29.c
124,2017.07.02,02-Jul-2017,2017.0,Invalid,COMOROS,Anjouan,Moya,Fishing,NaN,NaN,NaN,"Skull found in shark, a probable drowning & sc...",NaN,NaN,Shark involvement prior to death not confirmed,"Linfo, 7/3/2017",2017.07.02-Comoros.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.02,2017.07.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6125,1806.04.24,Aug-24-1806,1896.0,Sea Disaster,USA,NaN,NaN,NaN,Crew of the schooner Mary,M,NaN,Shark scavenged on the dead sailors,NaN,NaN,NaN,"Evening Post, 9/6/1806",1806.04.24-crew-of-the-Mary.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1806.04.24,1806.04.24
6126,1805.09.00,Sep-1805,1805.0,Invalid,USA,New York,"Sag Harbor, Suffolk County",NaN,NaN,M,NaN,human remains (male) found in sharks gut,NaN,NaN,Shark involvement prior to death unconfirmed,S.L. Mitchill (1814),1805.09.00-NY.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1805.09.00,1805.09.00
6147,1767.00.00,1767,1767.0,Invalid,FRANCE,Côte d'Azur,St. Tropez,Bathing,Samuel Matthews,M,NaN,Lacerations to arm & leg,NaN,NaN,Description of shark does not ring true,NaN,1767.00.00-Matthews.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1767.00.00,1767.00.00
6157,1733.00.00,1733,1733.0,Invalid,ICELAND,Bardestrand,Talkknefiord,NaN,NaN,NaN,NaN,"Partial hominid remains recovered from shark, ...",NaN,NaN,Shark involvement prior to death unconfirmed,E. Olafsen,1733.00.00-Iceland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1733.00.00,1733.00.00
6158,1723.00.00,1723,1723.0,Unprovoked,ROATAN,NaN,NaN,NaN,Philip Ashton,M,NaN,Struck on thigh,NaN,NaN,NaN,"C.Moore, GSAF",1730.00.00-Ashton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1723.00.00,1723.00.00

In [690]:
# 13 records that contain string injured in field 'injury'

df_3[['Injury','Fatal (Y/N)']][(df_3.Injury.str.lower().str.contains('injured')) & (df_3['Fatal (Y/N)'].isnull())].count()

Injury         13
Fatal (Y/N)     0
dtype: int64

In [ ]:
# been browsing them decide to assign them N for 'Fatal (Y/N)'
df_3.loc[list(df_3[['Injury','Fatal (Y/N)']][(df_3.Injury.str.lower().str.contains('injured')) & (df_3['Fatal (Y/N)'].isnull())].index), 'Fatal (Y/N)'] = 'N'

In [696]:
#Word minor in 'Injury' also strong indicator for non fatal
df_3[['Injury','Fatal (Y/N)']][(df_3.Injury.str.lower().str.contains('minor')) & (df_3['Fatal (Y/N)'].isnull())]

                                                 Injury Fatal (Y/N)
189                       Minor injuries to foot & toes         NaN
294   Minor injury to arm. Possibly caused by smalll...         NaN
306        Minor injury to wrist from Southern stingray         NaN
378    Minor injury when he attempted to touch a fish.          NaN
402                            Minor lacerations to leg         NaN
466                                  Minor cuts on feet         NaN
1003  Minor abrasions to legs when she was lifted on...         NaN
1064  Minor lacerations to left leg. nitially report...         NaN
1219                                     Minor injuries         NaN
1639                              Minor scratch on calf         NaN
2285                             Minor injuries to foot         NaN
2330                                       Minor injury         NaN
2752                                Minor injury to leg         NaN
3597       Minor lacerations & abrasions to lower leg.          NaN
5606                                     Minor injuries         NaN

In [698]:
list(df_3[['Injury','Fatal (Y/N)']][(df_3.Injury.str.lower().str.contains('minor')) & (df_3['Fatal (Y/N)'].isnull())].index)

[189,
 294,
 306,
 378,
 402,
 466,
 1003,
 1064,
 1219,
 1639,
 2285,
 2330,
 2752,
 3597,
 5606]

In [ ]:
#ASSIGNING N for non fatal with all that have string minor in injury field
df_3.loc[list(df_3[['Injury','Fatal (Y/N)']][(df_3.Injury.str.lower().str.contains('minor')) & (df_3['Fatal (Y/N)'].isnull())].index), 'Fatal (Y/N)'] = 'N'

In [712]:
#EXPERIMENTING WITH OTHER KEYWORDS
df_3[['Injury','Fatal (Y/N)']][(df_3.Injury.str.lower().str.contains('not deadly')) & (df_3['Fatal (Y/N)'].isnull())]

Empty DataFrame
Columns: [Injury, Fatal (Y/N)]
Index: []